In [15]:
%useLatestDescriptors
%use dataframe

import java.time.LocalDate
import java.io.File
import org.jetbrains.kotlinx.*
import org.jetbrains.kotlinx.dataframe.api.*
import org.jetbrains.kotlinx.dataframe.io.*

In [16]:
val simpleDf = dataFrameOf(
    "Name" to listOf("Alice", "Bob"),
    "Age" to listOf(25, 30)
)
simpleDf // Isolate the output

Name,Age
Alice,25
Bob,30

In [17]:
// https://kotlin.github.io/dataframe/data-schemas-in-kotlin-notebook.html#custom-data-schemas
interface Schema{
    val MainIsland : String?
    val Region : String?
    val Province : String?
    val LegislativeDistrict : String?
    val Municipality : String?
    val DistrictEngineeringOffice : String?
    val ProjectId : String?
    val ProjectName : String?
    val TypeOfWork : String?
    val FundingYear: Int?
    val ContractId : String?
    val ApprovedBudgetForContract: Double?
    val ContractCost: Double?
    val ActualCompletionDate: LocalDate?
    val Contractor : String?
    val ContractorCount: Int?
    val StartDate: LocalDate?
    val ProjectLatitude:Double?
    val ProjectLongitude: Double?
    val ProvincialCapital : String?
    val ProvincialCapitalLatitude: Double?
    val ProvincialCapitalLongitude: Double?
}

In [18]:
//https://kotlin.github.io/dataframe/convert.html
    // req 01 - read csv
    val path = "D:/01 KEI FILES/Academics and School/DLSU/TERM 4/CSADPRG S11/__MCO/MCO2/dpwh_flood_control_projects.csv"

    val raw = DataFrame
        .readCsv(
            File(path)
        )
    val ogCount = raw.count()
    val conv = raw
            .convert("FundingYear","ContractorCount").with{ it -> it.toString().toIntOrNull() }
            .convert("ApprovedBudgetForContract", "ContractCost", "ProjectLatitude", "ProjectLongitude", "ProvincialCapitalLatitude", "ProvincialCapitalLongitude").with{ it.toString().toDoubleOrNull() }
    val df = conv
        .convertTo<Schema>()
    df.schema().print()

    println("$ogCount")
    println("${df.count()}")
    df

MainIsland: String
Region: String
Province: String
LegislativeDistrict: String
Municipality: String?
DistrictEngineeringOffice: String
ProjectId: String
ProjectName: String
TypeOfWork: String
FundingYear: Int
ContractId: String
ApprovedBudgetForContract: Double?
ContractCost: Double?
ActualCompletionDate: java.time.LocalDate
Contractor: String
ContractorCount: Int
StartDate: java.time.LocalDate
ProjectLatitude: Double
ProjectLongitude: Double
ProvincialCapital: String
ProvincialCapitalLatitude: Double
ProvincialCapitalLongitude: Double
9855
9855

MainIsland,Region,Province,LegislativeDistrict,Municipality,DistrictEngineeringOffice,ProjectId,ProjectName,TypeOfWork,FundingYear,ContractId,ApprovedBudgetForContract,ContractCost,ActualCompletionDate,Contractor,ContractorCount,StartDate,ProjectLatitude,ProjectLongitude,ProvincialCapital,ProvincialCapitalLatitude,ProvincialCapitalLongitude
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526268LZ,Construction of Poblacion Flood Contr...,Construction of Flood Mitigation Stru...,2021,21PC0018,96500000.000000,92692943.800000,2022-10-03,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-03-18,18.250910,121.047570,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526368LZ,Construction of Cabicungan Flood Cont...,Construction of Flood Mitigation Stru...,2021,21PC0019,49000000.000000,47521251.300000,2022-11-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.511800,121.078290,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526369LZ,Construction of Sipa-San Mariano Floo...,Construction of Flood Mitigation Stru...,2021,21PC0010,47423180.000000,45942583.670000,2022-11-28,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.270230,121.420220,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00561270LZ,Construction of Sta. Filomena Floodwa...,Construction of Flood Mitigation Stru...,2021,21PC0067,9900000.000000,9900000.000000,2022-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.535660,121.080200,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00561652LZ,Construction of Sinigpit Flood Contro...,Construction of Flood Mitigation Stru...,2021,21PC0034,4950000.000000,4950000.000000,2022-09-23,ALEPHNORTH PEAK CONSTRUCTION AND DEVE...,1,2021-12-01,18.527230,121.096812,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 1st District Engineering Office,P00526367LZ,Construction of Nabuangan River (Upst...,Construction of Flood Mitigation Stru...,2021,21PB0004,39199819.730000,38292917.460000,2022-09-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-02,17.800000,121.315833,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 1st District Engineering Office,P00526270LZ,Construction of Nabuangan (Upstream) ...,Construction of Flood Mitigation Stru...,2021,21PB0013,82914680.000000,80309010.270000,2023-04-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-22,17.800278,121.308889,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620988LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0005,23519997.480000,22928490.310000,2022-11-02,PRIME MASTER CONST. AND DEV'T. CORP.,1,2022-02-09,17.823889,121.267778,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620472LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0004,15678924.680000,15680000.000000,2022-12-22,BAHRAMLEY CONSTRUCTION,1,2022-03-01,17.823889,121.267778,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620136LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2022,22PB0010,51761907.660000,51762600.000000,2023-05-30,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-04-04,17.818333,121.268611,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726398LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0009,72375000.000000,72375000.000000,2023-12-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-02-12,17.818642,121.268639,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726655LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0001,24500000.000000,24500000.000000,2023-06-22,GKA ENGINEERING AND CONSTRUCTION,1,2023-02-12,17.799808,121.282278,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00740313LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2023,23P00020,115793907.830000,115800000.000000,2024-02-29,JOMARCANN GENERAL CONSTRUCTION / RODE...,2,2023-04-12,17.819720,121.268330,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620989LZ,Construction of Cabicungan River Basi...,Construction of Flood Mitigation Stru...,2022,22PC0034,49000000.000000,49000000.000000,2022-12-12,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-02-09,18.527890,121.082970,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00640502LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2022,22PC0063,6930000.000000,6827260.010000,2023-09-15,E.C.V. CONSTRUCTION,1,2022-03-25,18.428870,121.189850,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620990LZ,Construction of Sta. Filomena Flood C...,Construction of Flood Mitigation Stru...,2022,22PC0068,49000000.000000,47169843.010000,2023-11-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-08-09,18.537150,121.086380,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735962LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0038,96500000.000000,96500000.000000,2024-02-07,TAGEL CORPORATION,1,2023-03-23,18.363270,120.974550,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735961LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0046,96500000.000000,96500000.000000,2024-03-11,TAGEL CORPORATION / E.C.V. CONSTRUCTION,2,2023-04-05,18.132430,121.078310,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735965LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0037,96500000.000000,93386847.090000,2024-03-15,TAGEL CORPORATION / AQUILA CONSTRUCTI...,2,2023-06-22,18.429090,121.189860,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),PUDTOL (APAYAO),Apayao 2nd District Engineering Office,P00620802LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2022,22PC0014,82025000.000000,79576285.450000,2023-07-31,ASC CONSTRUCTION & CONCRETE PRODUCTS ...,2,2022-03-31,18.206590,121.376530,Kabugao,18.021500,121.171600

In [19]:
//req 2 - basic validation BALIKAN!!!
// exclude invalid values
//val columns = listOf("MainIsland","Region","Province","LegislativeDistrict","Municipality","DistrictEngineeringOffice","ProjectId","ProjectName","TypeOfWork","FundingYear","ContractId","ApprovedBudgetForContract","ContractCost","ActualCompletionDate","Contractor","ContractorCount","StartDate","ProjectLatitude","ProjectLongitude","ProvincialCapital","ProvincialCapitalLatitude","ProvincialCapitalLongitude")
//
//val cleanDf = df.filter { row ->
//    columns.all{ col -> row[col] != null }
//}
val cleanDf = df.dropNulls()

val cleanCount= cleanDf.count()
println("original count: ${df.count()}")
println("new Count: $cleanCount")

original count: 9855
new Count: 9077

In [20]:
val validYearsDf = cleanDf.filter {
    val year = it["FundingYear"] as? Int
    year!=null && year in 2021..2023 }
val validYearsCount = validYearsDf.count()
println(validYearsCount)

println("clean Count: ${cleanDf.count()}")
println("clean Count: ${validYearsCount}")

6698
clean Count: 9077
clean Count: 6698

In [21]:
import java.time.temporal.ChronoUnit
val withNewCols = validYearsDf
    .add("CostSavings") {
        val approved = this["ApprovedBudgetForContract"] as Double
        val cost = this["ContractCost"] as Double
        (approved) - (cost)
    }
    .add("CompletionDelayDays") {
        val start = this["StartDate"] as LocalDate
        val end = this["ActualCompletionDate"] as LocalDate
        ChronoUnit.DAYS.between(start, end)
    }
val data = withNewCols

In [22]:
val df_1 = data
    .convert("ApprovedBudgetForContract","CostSavings","CompletionDelayDays").toDouble()
    .select("Region", "MainIsland", "ApprovedBudgetForContract", "CostSavings", "CompletionDelayDays")
var groupedByRegion = df_1
//    .groupBy{ it["Region"], it["MainIsland"]}
    .groupBy("Region", "MainIsland")
    .aggregate{
        sumOf { it["ApprovedBudgetForContract"]  as Double} into "TotalBudget"
        medianOf {  it["CostSavings"] as Double} into "MedianSavings"
        meanOf {  it["CompletionDelayDays"] as Double} into "AvgDelay"

    //percentage of projects with delays >30 days by Region and MainIsland
//        add("HighDelayPct") { row ->
//            val totalProjects = row.count()
//            val delayAbove30: Double = row.count { (it["CompletionDelayDays"] as Double) > 30}
//            (delayAbove30 / totalProjects) * 100.00
//        }
    }
    .add("EfficiencyScore") {
        val median = it["MedianSavings"] as Double
        val avg = it["AvgDelay"] as Double
        median/avg
    }

groupedByRegion

Region,MainIsland,TotalBudget,MedianSavings,AvgDelay,EfficiencyScore
Cordillera Administrative Region,Luzon,11716720926.290005,2072.120000,234.748899,8.826964
National Capital Region,Luzon,34512858340.750010,286227.210000,272.116715,1051.854570
Region I,Luzon,23331355341.590008,2332.970000,227.151899,10.270528
Region II,Luzon,20227511049.350002,10000.000000,248.870000,40.181621
Region III,Luzon,60816863675.419980,2215.650000,212.897706,10.407111
Region IV-A,Luzon,32433450465.209995,581.540000,257.522222,2.258213
Region IV-B,Luzon,21123321654.840000,2973.580000,259.819113,11.444809
Region IX,Mindanao,3377302460.310000,30006.930000,305.282051,98.292480
Region V,Luzon,40386863421.270035,240.950000,236.955385,1.016858
Region VI,Visayas,18050187896.440002,650.650000,308.705234,2.107674
Region VII,Visayas,25790800258.260000,29.030000,245.266968,0.118361
Region VIII,Visayas,16898327608.319994,55157.440000,247.755906,222.628154
Region X,Mindanao,19013059584.800000,3642.220000,340.241379,10.704812
Region XI,Mindanao,15224989180.300005,16.195000,276.520161,0.058567
Region XII,Mindanao,10690650674.099998,13911.505000,266.139785,52.271422
Region XIII,Mindanao,17175416383.910000,228.540000,321.142857,0.711646